
name: Push Image

on: push
#on:
#  push:
#    tags:
#      - "v*"
permissions:
  contents: read

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

       #Python is required because ct lint runs Yamale and yamllint which require Python.
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.13'

      - name: Build the Docker image
        run: |
          echo "login aliyun registry"
          docker login --username=huiwq1990@163.com -p Cr@123456 registry.cn-beijing.aliyuncs.com/huiwq1990/public
          echo "build image"
          tag=cosyvoice-v0.0.3
          docker buildx build --platform=linux/amd64 --push -f docker/Dockerfile -t registry.cn-beijing.aliyuncs.com/huiwq1990/public:${tag}-amd64 .
          #docker buildx build --platform=linux/amd64 --push -f runtime/python/Dockerfile -t registry.cn-beijing.aliyuncs.com/huiwq1990/public:${tag}-amd64 .
